apiVersion: v1
kind: Service
metadata:
  name: ms-sql-server-service
spec:
  selector:
    app: ms-sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-server-deployment
spec:
  selector:
    matchLabels:
      app: ms-sql-server
  template:
    metadata:
      labels:
        app: ms-sql-server
    spec:
      containers:
        - name: ms-sql-server-container
          image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "HDLCrin8*"
            - name: MSSQL_PID
              value: Express
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-resources-api-service
spec:
  selector:
    app: dotnet-resources-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resources-api-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-resources-api
  template:
    metadata:
      labels:
        app: dotnet-resources-api
    spec:
      containers:
        - name: dotnet-resources-api-container
          image: jcortizs/dotnet_resources_api
          env:
            - name: ms-sql-server
              #value: "ms-sql-server"
              value: "localhost"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=tcp:localhost,1433;Database=resources_db;Trusted_Connection=False;TrustServerCertificate=True;MultipleActiveResultSets=true;User ID=sa;Password=HDLCrin8*;"
          ports:
            - containerPort: 8080
            - containerPort: 1433
