version: '0.0.1'
services:
  ms-sql-server: 
    #image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HDLCrin8*"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  resources-api:
    image: jcortizs/dotnet_resources_api
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"