// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_resources_api.Models;

#nullable disable

namespace dotnet_resources_api.Migrations
{
    [DbContext(typeof(resources_context))]
    [Migration("20230924235030_initial_model_create")]
    partial class initial_model_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnet_resources_api.Models.Classes", b =>
                {
                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rowid"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<int>("class_order")
                        .HasColumnType("int");

                    b.Property<string>("class_text")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime");

                    b.HasKey("rowid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("dotnet_resources_api.Models.Files", b =>
                {
                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rowid"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<int>("class_order")
                        .HasColumnType("int");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime");

                    b.Property<string>("filedata")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("rowid");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
