// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourcesAPI.Models;

#nullable disable

namespace ResourcesAPI.Migrations
{
    [DbContext(typeof(ResourcesContext))]
    partial class ResourcesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResourcesAPI.Models.Classes", b =>
                {
                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rowid"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<int>("class_order")
                        .HasColumnType("int")
                        ;//.HasDefaultValue(0);

                    b.Property<string>("class_text")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime")
                        ;//.HasDefaultValueSql("GETDATE()");

                    b.HasKey("rowid");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("ResourcesAPI.Models.Files", b =>
                {
                    b.Property<int>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rowid"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<int>("class_order")
                        .HasColumnType("int")
                        ;//.HasDefaultValue(0);

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdon")
                        .IsRequired()
                        .HasColumnType("datetime")
                        ;//.HasDefaultValueSql("GETDATE()");

                    b.Property<string>("filedata")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("rowid");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
